config/routes.rb
Rails.application.routes.draw do

  root to: "articles#index"

  resources :articles do
      resources :comments
  end

  resources :tags

end

app/models/article.rb
class Article < ActiveRecord::Base
    has_many :comments
    has_many :attachments

    has_many :taggings
    has_many :tags, through: :taggings

    def tag_list
	tags.collect(&:name).join ','
    end

    def tag_list=(tag_names)
	uniq_tag_names = tag_names.split(',').map { |tag| tag.strip.downcase }.uniq
	tag_instances = uniq_tag_names.map do |tag_name|
	    Tag.find_or_create_by(name: tag_name)
	end

	self.tags = tag_instances
    end

    def image=(image)
	
	attachments.new( image: image )
    end
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
    belongs_to :article
    has_attached_file :image
    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/png", "image/jpeg"]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/tag.rb
class Tag < ActiveRecord::Base
    has_many :taggings
    has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  include ArticlesHelper
  
  def index
      @articles = Article.all
  end

  def show
      @article = Article.find( params[:id] )
      @comment = Comment.new
      @comment.article_id = @article.id
  end

  def new
      @article = Article.new
      @attachment = Attachment.new
  end

  def create
      @article = Article.new( article_params )
      @article.save
      redirect_to article_path(@article)
  end

  def edit
      @article = Article.find( params[:id] )
  end

  def update
      @article = Article.find( params[:id] )
      @article.update( article_params )

      flash.notice = "Article updated."

      redirect_to articles_path
  end

  def destroy
      @article = Article.find( params[:id] )
      @article.destroy

      redirect_to articles_path
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    include CommentsHelper
    def create
	@comment = Comment.new( comment_params )
	@comment.article_id = params[:article_id]

	@comment.save
	redirect_to article_path(@comment.article)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

    def index
	@tags = Tag.all
    end

    def show
	@tag = Tag.find( params[:id] )
    end

    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
    def article_params
	params.require(:article).permit(:title, :body, :tag_list, :image)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
    def comment_params
	params.require(:comment).permit(:author_name, :body)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.erb
<p> 
    Comment by :
    <%= comment.author_name %>
</p>
<p>
    Body : 
    <%= comment.body %>
</p>
    
    

app/views/articles/_form.html.erb
<%= form_for(@article, { multipart: true }) do |form| %>
    <p>
	<%= form.label :title %>
	<%= form.text_field :title %>
    </p>

    <p>
	<%= form.label :body %>
	<%= form.text_area :body %>
    </p>

    <p>
	<%= form.label :tag_list %>
	<%= form.text_field :tag_list %>
    </p>

    <p>
	<%= form.label :image %>
	<%= form.file_field :image %>
    </p>

    <%= form.submit %>
<% end %>

app/views/articles/edit.html.erb
<h3>Edit article</h3>

<%= render partial: 'articles/form' %>

app/views/articles/index.html.erb
<h2> List of articles : </h2>

<% if @articles.empty? %>
    <p>Sorry there aren't any articles created.</p>
<% else %>
    <% @articles.each do |article| %>
	<strong>
	    <%= link_to article.title, article_path(article) %>
	</strong>
    <br>
    <% end %>
<% end %>

<%= link_to "Create an article", new_article_path %>

app/views/articles/new.html.erb
<h3>Create a new article</h3>

<%= render partial: 'articles/form' %>

app/views/articles/show.html.erb
<h2>
    <%= @article.title %>
</h2>

<p>
    <%= @article.body %>
</p>

<br>
<p> Tags : 
<% @article.tags.each do |tag| %>
	<em> <%= link_to tag.name, tag_path(tag) %> </em> 
    <% end %>
</p>

<% unless @article.attachments.empty? %>
    <h3>Images : </h3>
    <%= @article.attachments.each do |attachment| %>
	<%= image_tag attachment.image.url %>
	<br>
    <% end %>
<% end %>

<% unless @article.comments.empty? %>
    <h3>Comments ( <%= @article.comments.size %> )</h3>
<% end %>
<%= render partial: "articles/comment", collection: @article.comments %>
<%= render partial: "comments/form" %>
<%= link_to "Edit this article", edit_article_path(@article) %>
<%= link_to "Delete this article", article_path(@article) , method: :delete%>
<%= link_to "Articles", articles_path %>

app/views/comments/_form.html.erb
<h4>Post a comment buddy.</h4>
<%= form_for [@article, @comment] do |form| %>
    <p>
	<%= form.label :author_name %>
	<br>
	<%= form.text_field :author_name %>
    </p>

    <p>
	<%= form.label :body %>
	<br>
	<%= form.text_area :body %>
    </p>
    <p>
	<%= form.submit %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <em> <%= flash.notice %> </em>

<%= yield %>

</body>
</html>

app/views/tags/index.html.erb
<h3>List of all tags</h3>
<% @tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
<% end %>

app/views/tags/show.html.erb
<h3>List of articles with tag <strong><%= @tag.name %></h3>

<% @tag.articles.each do |article| %>
    <%= link_to article.title, article_path(article) %>
<% end %>